### ISSUE TITLE
记 wsl (bash on windows) 终端折腾

### ISSUE THREAD

**Issue by shynome** [shynome/shynome.github.io#4]
`wsl` 和 `vscode` 相性越来越好了, 但是 `git` 还是不行, 只能用 `git bash` 来提交, 但也是能接受的. 下面是我的 `wsl` 的折腾

### 安装 `wsl`

按 `win`+`x` 在管理员权限下的 `powershell` 执行以下命令开启 linux 子系统
```powershell
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
```

然后去应用商店里下载 `ubuntu` 或者其他你喜欢的 `linux` 发行版

下载地址: <https://aka.ms/wslstore>

ps: 在输入用户名的时候关闭终端, 再次打开就直接是 `root` 用户登录了

### `wsl` 镜像加速

镜像加速官方帮助文档: <https://mirrors.ustc.edu.cn/help/ubuntu.html>

官方文档只替换了一次, 但实际上要替换两次
```
sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && \
sed -i 's/security.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
```

### `wsl` 终端配置

现在有两个 `wsl mintty`:

- <https://github.com/mintty/wsltty>
- <https://github.com/goreliu/wsl-terminal>

我选择了 `wsl-terminal` , 这个有中文支持, 而且图标看起来也挺精致的, 配置如下:

- 下载 `wsl-terminal` 客户端: <https://github.com/goreliu/wsl-terminal/releases>
- 解压到 OneDrive 文件夹方便同步设置
- 在解压好的 `tools` 目录里打开 `powershell`
  - `wscript.exe ./1-add-open-wsl-terminal-here-menu.js` 把 `wsl-terminal` 添加到右键菜单里
  - `wscript.exe ./4-create-start-menu-shortcut.js` 创建一个开始菜单快捷方式，指向 open-wsl -C ~
- `win` + `r` 输入 `%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs` 进入该目录
- 修改 `open-wsl.lnk` 文件属性中的快捷键为 `ctrl` + `alt` + `T`, 与 `linux` 的 `terminal` 快捷键一致

### `wsl` 和 `git bash` 共享 ssh 配置

在 `cmd` 下执行以下 `ssh` 配置目录共享命令

```cmd
mklink /D "%userprofile%/.ssh" "%userprofile%\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs\root\.ssh"
```

### `docker` 命令行配置

```sh
# wsl 也需要安装 docker
curl https://get.docker.com | sh
```

`docker for windows` 的设置里把 `Expose daemon on tcp://localhost:2375` 勾上   

![image](https://user-images.githubusercontent.com/17316043/41202469-0594de20-6cfc-11e8-95da-f5d7f1bca885.png)

如果 `~/.bashrc` 里没有设置 `export DOCKER_HOST=tcp://localhost:2375` 的话, 使用 `docker` 命令是会报错的, 下面是快速设置脚本
```sh
echo 'which docker.exe>/dev/null && export DOCKER_HOST=tcp://localhost:2375' >> ~/.bashrc
# 重新加载bash配置文件
source ~/.bashrc 
```

### 结束

到此我的 `wsl` 配置完成了

**Comment by xnng** [comment]
老哥知不知道怎么在 git bash 中打开 wsl，每次会卡住不动

**Comment by shynome** [comment]
@xnng 可能需要 `winpty wsl` 这样子. 目前我已经不用 `wsl` , 软件生态不兼容太糟心了, 不折腾了

**Comment by xnng** [comment]
@shynome 对，这样是可以的。

这东西确实不好用，不管是性能还是体验还不如虚拟机，我现在测试代码直接用服务器。
